import { MediaAsset } from "./types";

export const initialMediaPart2: MediaAsset[] = [
  {
    id: "media-consolto-01",
    url: "/images/social-media/startup-consolto-designs.webp",
    storageType: "local",
    filename: "startup-consolto-designs.webp",
    altText: "تصاميم سوشيال ميديا ومطبوعات لعيادات وشركات ناشئة - كونسلتو",
    title: "أعمال تصاميم السوشيال لشركة كونسلتو",
    caption: "معرض أعمال الحملات التسويقية",
    description: "تصميم بوستات وبنرات إعلانية",
    dimensions: { width: 1080, height: 1350 },
    fileSizeKb: 180,
    mimeType: "image/webp",
    category: "social",
    tags: ["أعمال", "سوشيال", "تصاميم"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-ayg-01",
    url: "/images/social-media/ayg-partners-designs.webp",
    storageType: "local",
    filename: "ayg-partners-designs.webp",
    altText: "تصميم بروفايل وبوستات سوشيال ميديا لشركة AYG Partners",
    title: "هوية سوشيال ميديا AYG Partners",
    caption: "أعمال بروفايل الشركات والمطبوعات",
    dimensions: { width: 1080, height: 1080 },
    fileSizeKb: 125,
    mimeType: "image/webp",
    category: "social",
    tags: ["شركاء", "سوشيال ميديا", "أعمال"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-yousry-01",
    url: "/images/social-media/amm-yousry-designs.webp",
    storageType: "local",
    filename: "amm-yousry-designs.webp",
    altText: "تصاميم مطبوعات وسوشيال ميديا مطعم عم يسري",
    title: "تصاميم مطعم عم يسري",
    caption: "منيو وعلب ومطبوعات مطاعم",
    dimensions: { width: 1080, height: 1080 },
    fileSizeKb: 135,
    mimeType: "image/webp",
    category: "social",
    tags: ["مطاعم", "علب", "منيو", "تغليف"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-testimonial-01",
    url: "/images/testimonial-skip-01.webp",
    storageType: "local",
    filename: "testimonial-skip-01.webp",
    altText: "عميل راضي عن جودة طباعة وتغليف إطبعلي",
    title: "آراء وتقييمات العملاء 01",
    dimensions: { width: 400, height: 400 },
    fileSizeKb: 45,
    mimeType: "image/webp",
    category: "general",
    tags: ["تقييمات", "عملاء"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-testimonial-02",
    url: "/images/testimonial-skip-02.webp",
    storageType: "local",
    filename: "testimonial-skip-02.webp",
    altText: "شهادة عميل في سرعة ودقة تسليم مطبوعات إطبعلي",
    title: "آراء وتقييمات العملاء 02",
    dimensions: { width: 400, height: 400 },
    fileSizeKb: 48,
    mimeType: "image/webp",
    category: "general",
    tags: ["تقييمات", "عملاء"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-action-01",
    url: "/images/actions/action-001.webp",
    storageType: "local",
    filename: "action-001.webp",
    altText: "أدلة وتجهيزات طباعة الأوفست ومواصفات ماكينات هايدلبرج",
    title: "دليل تجهيز ملفات الطباعة الأوفست",
    dimensions: { width: 800, height: 500 },
    fileSizeKb: 72,
    mimeType: "image/webp",
    category: "products",
    tags: ["أوفست", "تجهيز", "مقالات"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-action-02",
    url: "/images/actions/action-002.webp",
    storageType: "local",
    filename: "action-002.webp",
    altText: "ماكينات السلوفان والبصمة الحرارية لعلب الكرتون",
    title: "مرحلة السلوفان والسكينة",
    dimensions: { width: 800, height: 500 },
    fileSizeKb: 78,
    mimeType: "image/webp",
    category: "products",
    tags: ["سلوفان", "بصمة", "علب"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-action-03",
    url: "/images/actions/action-003.webp",
    storageType: "local",
    filename: "action-003.webp",
    altText: "طباعة الأكياس الورقية الكرافت الفاخرة للعلامات التجارية",
    title: "أكياس كرافت مخصصة باللوجو",
    dimensions: { width: 800, height: 500 },
    fileSizeKb: 85,
    mimeType: "image/webp",
    category: "products",
    tags: ["أكياس", "كرافت", "لوجو"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
