import { MediaAsset } from "./types";

export const initialMediaPart1: MediaAsset[] = [
  {
    id: "media-hero-01",
    url: "/images/hero-image.webp",
    storageType: "local",
    filename: "hero-image.webp",
    altText: "ماكينات طباعة وتغليف حديثة - خطوط إنتاج مطبعة إطبعلي الفاخرة",
    title: "ماكينات طباعة وتغليف متطورة",
    caption: "صورة الغلاف الرئيسية لقسم الطباعة الفاخرة في إطبعلي",
    description: "تُظهر الماكينات الحديثة وتقنيات الأوفست والديجيتال",
    dimensions: { width: 1200, height: 800 },
    fileSizeKb: 145,
    mimeType: "image/webp",
    category: "branding",
    tags: ["سيو", "طباعة", "هيرو", "إطبعلي"],
    usedIn: [{ type: "article", id: "az-seo-aeo-001", title: "مستقبل الطباعة الرقمية والسيو" }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-brand-hero",
    url: "/images/brand-hero-business.webp",
    storageType: "local",
    filename: "brand-hero-business.webp",
    altText: "فريق عمل وتصنيع هويات الشركات والطباعة التجارية الفاخرة",
    title: "الهوية البصرية للشركات والأعمال",
    caption: "حلول البراندينج والمطبوعات للمؤسسات",
    description: "صورة عالية الدقة لخدمات طباعة الشركات والهويات",
    dimensions: { width: 1400, height: 900 },
    fileSizeKb: 210,
    mimeType: "image/webp",
    category: "branding",
    tags: ["بيزنس", "هوية", "شركات", "طباعة"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-offer-01",
    url: "/images/social-media/az-social-offer-99egp.webp",
    storageType: "local",
    filename: "az-social-offer-99egp.webp",
    altText: "عرض تصميم السوشيال ميديا وهوية الشركات والمطابع",
    title: "عرض السوشيال ميديا والطباعة الفورية",
    caption: "بانر الترويج للعروض المباشرة",
    description: "صورة عالية الجودة لعروض السوشيال ميديا والتغليف",
    dimensions: { width: 1080, height: 1080 },
    fileSizeKb: 98,
    mimeType: "image/webp",
    category: "social",
    tags: ["عروض", "سوشيال ميديا", "تسويق", "تصاميم"],
    usedIn: [{ type: "article", id: "social-media-growth", title: "كيف تبني هوية بصرية قوية لعلامتك" }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-box-01",
    url: "/images/brand-offer-easel.webp",
    storageType: "local",
    filename: "brand-offer-easel.webp",
    altText: "استاند خشبي وعينات تغليف وعلب كرتون فاخرة للمنتجات",
    title: "استاند وعينات التغليف الكاستم",
    caption: "نموذج لتصنيع الاستاندات والعلب",
    description: "عينات تغليف وعرض تجاري",
    dimensions: { width: 1000, height: 1000 },
    fileSizeKb: 112,
    mimeType: "image/webp",
    category: "products",
    tags: ["علب", "تغليف", "منتجات", "استاندات"],
    usedIn: [{ type: "product", id: "cfg-luxury-box", title: "علب كرتون دوبلكس مقوى كاستم" }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-badge-01",
    url: "/images/brand-logo-badge.webp",
    storageType: "local",
    filename: "brand-logo-badge.webp",
    altText: "شارة شيلد شعار إطبعلي الرسمي للعلامات التجارية",
    title: "شارة شعار إطبعلي",
    caption: "ختم الاعتماد الرسمي للشعار",
    dimensions: { width: 600, height: 600 },
    fileSizeKb: 68,
    mimeType: "image/webp",
    category: "branding",
    tags: ["شارة", "لوجو", "ختم"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-brand-02",
    url: "/images/brand-3d-creative.webp",
    storageType: "local",
    filename: "brand-3d-creative.webp",
    altText: "عناصر بصرية ثلاثية الأبعاد لهوية البراند والطباعة",
    title: "عناصر ثلاثية الأبعاد للإعلانات",
    caption: "تصميم ثلاثي الأبعاد ثلاثي المحاور للهوية",
    description: "استخدام ثري دي في إبراز المنتجات والتغليف",
    dimensions: { width: 1200, height: 900 },
    fileSizeKb: 160,
    mimeType: "image/webp",
    category: "branding",
    tags: ["3D", "هوية", "تصميم"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "media-logo-01",
    url: "/images/ICON-LOGO-SITE.webp",
    storageType: "local",
    filename: "ICON-LOGO-SITE.webp",
    altText: "شعار منصة إطبعلي - المطبعة الرقمية والهويات التجارية الفاخرة",
    title: "لوجو إطبعلي الرسمي",
    caption: "أيقونة اللوجو الرئيسية للموقع",
    description: "الأيقونة المعتمدة في الهيدر والفوتر والـ OpenGraph",
    dimensions: { width: 512, height: 512 },
    fileSizeKb: 34,
    mimeType: "image/webp",
    category: "branding",
    tags: ["لوجو", "شعار", "إطبعلي"],
    usedIn: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
