import { VisualConfigurator } from "../types";

export const taperedTwoToneMugConfigurator: VisualConfigurator = {
  id: "cfg-tapered-two-tone-mug",
  name: "مج سيراميك كافيه مخروطي فاخر (Tapered Two-Tone Mug)",
  productId: "prod-tapered-two-tone-mug",
  style: "style1",
  canvasWidth: 1000,
  canvasHeight: 1000,
  basePrice: 120,
  views: [
    { id: "v-front", name: "المنظور 1 - الأمامي (Front View)", canvasWidth: 1000, canvasHeight: 1000 },
    { id: "v-angle", name: "المنظور 2 - العلوي المائل (Elevated Angle)", canvasWidth: 1000, canvasHeight: 1000 },
    { id: "v-handle", name: "المنظور 3 - المقبض والجانب (Side View)", canvasWidth: 1000, canvasHeight: 1000 },
  ],
  hotspots: [],
  groups: [
    // Group 1: خامة المج - المنظور 1: الأمامي
    {
      id: "grp-tt-front",
      title: "خامة المج - المنظور الأمامي (Front View)",
      controlType: "color",
      required: true,
      multiple: false,
      initialState: "open",
      options: [
        {
          id: "opt-tt-front-green",
          name: "أخضر زمردي نضاري (Forest Green)",
          controlType: "color",
          colorHex: "#2E7D32",
          priceAdd: 0,
          activeOnLoad: true,
          imageUrl: "/images/products/mugs/green/Free_Mug_Mockup_1.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-front",
        },
        {
          id: "opt-tt-front-brown",
          name: "بني كراميل ذهبي ملكي (Caramel Gold)",
          controlType: "color",
          colorHex: "#C28B38",
          priceAdd: 18,
          activeOnLoad: false,
          imageUrl: "/images/products/mugs/brown-gold/Free_Mug_Mockup_1.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-front",
        },
      ],
    },
    // Group 2: خامة المج - المنظور 2: العلوي المائل
    {
      id: "grp-tt-angle",
      title: "خامة المج - المنظور العلوي المائل (Elevated Angle)",
      controlType: "color",
      required: true,
      multiple: false,
      initialState: "open",
      options: [
        {
          id: "opt-tt-angle-green",
          name: "أخضر زمردي نضاري (Forest Green)",
          controlType: "color",
          colorHex: "#2E7D32",
          priceAdd: 0,
          activeOnLoad: true,
          imageUrl: "/images/products/mugs/green/Free_Mug_Mockup_2.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-angle",
        },
        {
          id: "opt-tt-angle-brown",
          name: "بني كراميل ذهبي ملكي (Caramel Gold)",
          controlType: "color",
          colorHex: "#C28B38",
          priceAdd: 18,
          activeOnLoad: false,
          imageUrl: "/images/products/mugs/brown-gold/Free_Mug_Mockup_2.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-angle",
        },
      ],
    },
    // Group 3: خامة المج - المنظور 3: المقبض والجانب
    {
      id: "grp-tt-handle",
      title: "خامة المج - منظور المقبض والجانب (Side View)",
      controlType: "color",
      required: true,
      multiple: false,
      initialState: "open",
      options: [
        {
          id: "opt-tt-handle-green",
          name: "أخضر زمردي نضاري (Forest Green)",
          controlType: "color",
          colorHex: "#2E7D32",
          priceAdd: 0,
          activeOnLoad: true,
          imageUrl: "/images/products/mugs/green/Free_Mug_Mockup_3.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-handle",
        },
        {
          id: "opt-tt-handle-brown",
          name: "بني كراميل ذهبي ملكي (Caramel Gold)",
          controlType: "color",
          colorHex: "#C28B38",
          priceAdd: 18,
          activeOnLoad: false,
          imageUrl: "/images/products/mugs/brown-gold/Free_Mug_Mockup_3.jpg",
          x: 50,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          viewId: "v-handle",
        },
      ],
    },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
