import { VisualConfigurator } from "../types";

export const packagingConfigurators: VisualConfigurator[] = [
  {
    id: "cfg-luxury-box",
    name: "علب هدايا وتغليف فاخرة (Luxury Packaging Box)",
    productId: "prod-packaging-rigid-box",
    style: "style1",
    canvasWidth: 1000,
    canvasHeight: 1000,
    basePrice: 45,
    views: [
      { id: "v-front", name: "المنظور الأمامي (Front View)", canvasWidth: 1000, canvasHeight: 1000 },
      { id: "v-open", name: "العلبة مفتوحة (Open Box Inside)", canvasWidth: 1000, canvasHeight: 1000 },
      { id: "v-side", name: "المنظور الجانبي (Side View)", canvasWidth: 1000, canvasHeight: 1000 },
    ],
    hotspots: [
      { id: "hs-1", viewId: "v-front", x: 50, y: 35, title: "بصمة الفويل واللوجو", targetGroupId: "grp-foil" },
      { id: "hs-2", viewId: "v-front", x: 80, y: 70, title: "خامة الكرتون الخارجي", targetGroupId: "grp-color" },
    ],
    groups: [
      {
        id: "grp-color",
        title: "لون وخامة العلبة (Base Color)",
        controlType: "color",
        required: true,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-c-red", name: "أحمر قرمزي ملكي", controlType: "color", colorHex: "#C93B41", priceAdd: 0, activeOnLoad: true, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-c-black", name: "أسود فاحم مطفي", controlType: "color", colorHex: "#1C1C1C", priceAdd: 5, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-c-gold", name: "ذهبي شامبين معدني", controlType: "color", colorHex: "#D4AF37", priceAdd: 12, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-c-orange", name: "برتقالي هيرميس كلاسيك", controlType: "color", colorHex: "#E5833B", priceAdd: 8, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-c-brown", name: "بني شيكولاتة داكن", controlType: "color", colorHex: "#4E2E1E", priceAdd: 6, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
        ],
      },
      {
        id: "grp-foil",
        title: "المعالجة الذهبية واللوجو (Finishing & Foil)",
        controlType: "icon",
        required: false,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-foil-gold", name: "بصمة فويل ذهبي حراري", controlType: "icon", iconUrl: "✨", priceAdd: 18, activeOnLoad: true, x: 50, y: 35, width: 45, height: 25, zIndex: 4, viewId: "v-front" },
          { id: "opt-foil-silver", name: "بصمة ليزر فضي براق", controlType: "icon", iconUrl: "❄️", priceAdd: 15, activeOnLoad: false, x: 50, y: 35, width: 45, height: 25, zIndex: 4, viewId: "v-front" },
          { id: "opt-foil-uv", name: "سبوت UV بارز ملمع", controlType: "icon", iconUrl: "💧", priceAdd: 10, activeOnLoad: false, x: 50, y: 35, width: 45, height: 25, zIndex: 4, viewId: "v-front" },
        ],
      },
      {
        id: "grp-text",
        title: "كتابة الاسم أو الإهداء (Custom Engraving)",
        controlType: "inline_text",
        required: false,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-text-slot", name: "حفر ليزري لاسم الشركة", controlType: "inline_text", priceAdd: 15, activeOnLoad: false, x: 50, y: 78, width: 60, height: 15, zIndex: 5, viewId: "v-front", description: "اكتب اسم الشركة أو الإهداء ليتم حفره بالليزر بدقة فائقة." },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cfg-canvas-tote",
    name: "حقيبة توت باج قماش كانفاس (Canvas Tote Bag)",
    productId: "prod-canvas-tote",
    style: "style1",
    canvasWidth: 1000,
    canvasHeight: 1000,
    basePrice: 95,
    views: [
      { id: "v-front", name: "الوجه الأمامي (Front View)", canvasWidth: 1000, canvasHeight: 1000 },
      { id: "v-back", name: "الوجه الخلفي (Back View)", canvasWidth: 1000, canvasHeight: 1000 },
    ],
    hotspots: [
      { id: "hs-tb-1", viewId: "v-front", x: 50, y: 52, title: "مساحة الصورة والطباعة", targetGroupId: "grp-tote-print" },
    ],
    groups: [
      {
        id: "grp-tote-color",
        title: "لون قماش الكانفاس الطبيعي (Canvas Color)",
        controlType: "color",
        required: true,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-tbc-offwhite", name: "أوف وايت طبيعي (خام)", controlType: "color", colorHex: "#F3EFE6", priceAdd: 0, activeOnLoad: true, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-tbc-black", name: "أسود كلاسيك", controlType: "color", colorHex: "#1A1A1A", priceAdd: 10, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-tbc-navy", name: "كحلي بحري", controlType: "color", colorHex: "#1E2B45", priceAdd: 10, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
        ],
      },
      {
        id: "grp-tote-print",
        title: "مساحة وحجم الطباعة (Print Area 25x30 cm)",
        controlType: "icon",
        required: false,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-tbp-standard", name: "طباعة أمامية قياسية (25x30 cm)", controlType: "icon", iconUrl: "👜", priceAdd: 0, activeOnLoad: true, x: 50, y: 52, width: 60, height: 60, zIndex: 2, viewId: "v-front" },
          { id: "opt-tbp-double", name: "طباعة ملونة على الوجهين (Double Sided)", controlType: "icon", iconUrl: "🔄", priceAdd: 25, activeOnLoad: false, x: 50, y: 52, width: 60, height: 60, zIndex: 2, viewId: "v-front" },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cfg-travel-tumbler",
    name: "ترمس حراري استانلس بشاشة ديجيتال (Smart Tumbler)",
    productId: "prod-travel-tumbler",
    style: "style1",
    canvasWidth: 1000,
    canvasHeight: 1000,
    basePrice: 220,
    views: [
      { id: "v-front", name: "المنظور الأمامي والشاشة (Front & Screen)", canvasWidth: 1000, canvasHeight: 1000 },
      { id: "v-cap", name: "الغطاء الذكي الحساس (Touch Cap)", canvasWidth: 1000, canvasHeight: 1000 },
      { id: "v-360", name: "دوران شامل (360° View)", canvasWidth: 1000, canvasHeight: 1000 },
    ],
    hotspots: [
      { id: "hs-tm-1", viewId: "v-front", x: 50, y: 50, title: "موضع حفر اللوجو أو الصورة", targetGroupId: "grp-tumbler-logo" },
      { id: "hs-tm-2", viewId: "v-front", x: 50, y: 78, title: "حفر الاسم المخصص", targetGroupId: "grp-tumbler-text" },
    ],
    groups: [
      {
        id: "grp-tumbler-color",
        title: "لون الترمس الخارجي (Tumbler Color)",
        controlType: "color",
        required: true,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-tmc-black", name: "أسود مطفي فاخر", controlType: "color", colorHex: "#1F1F1F", priceAdd: 0, activeOnLoad: true, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-tmc-white", name: "أبيض لؤلؤي", controlType: "color", colorHex: "#F8F8F8", priceAdd: 0, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-tmc-red", name: "أحمر قرمزي A.Z", controlType: "color", colorHex: "#C93B41", priceAdd: 10, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
          { id: "opt-tmc-blue", name: "أزرق ملكي", controlType: "color", colorHex: "#1D4ED8", priceAdd: 10, activeOnLoad: false, x: 50, y: 50, width: 90, height: 90, zIndex: 1, viewId: "v-front" },
        ],
      },
      {
        id: "grp-tumbler-logo",
        title: "طريقة الحفر أو الطباعة (Custom Engraving)",
        controlType: "icon",
        required: false,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-tml-laser", name: "حفر ليزري ميكروني فضي دائم", controlType: "icon", iconUrl: "⚡", priceAdd: 0, activeOnLoad: true, x: 50, y: 50, width: 45, height: 45, zIndex: 2, viewId: "v-front" },
          { id: "opt-tml-uv", name: "طباعة ألوان UV بارزة ملونة", controlType: "icon", iconUrl: "🎨", priceAdd: 20, activeOnLoad: false, x: 50, y: 50, width: 45, height: 45, zIndex: 2, viewId: "v-front" },
        ],
      },
      {
        id: "grp-tumbler-text",
        title: "حفر الاسم المخصص (Name Engraving)",
        controlType: "inline_text",
        required: false,
        multiple: false,
        initialState: "open",
        options: [
          { id: "opt-tmt-name", name: "اسم الشخص أو عبارة الإهداء", controlType: "inline_text", priceAdd: 10, activeOnLoad: false, x: 50, y: 78, width: 50, height: 12, zIndex: 3, viewId: "v-front", description: "أدخل الاسم المطلوب حفره بالليزر." },
        ],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
